overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
