name: CI (Check, Verify, and Build)

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v5

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true
          run-install: false

      - name: Install Dependencies
        run: vp i --frozen-lockfile -- --trust-lockfile

      - name: Check Files
        run: vpr check

      - name: Verify Types
        run: vpr typecheck

      - name: Build Nuxt
        run: vpr build
